#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v24
# autospec commit: a88ffdc
#
Name     : perl-MooseX-Types
Version  : 0.51
Release  : 18
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/MooseX-Types-0.51.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/MooseX-Types-0.51.tar.gz
Summary  : 'Organise your Moose types in libraries'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-MooseX-Types-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(ExtUtils::Config)
BuildRequires : perl(ExtUtils::Helpers)
BuildRequires : perl(ExtUtils::InstallPaths)
BuildRequires : perl(Module::Build::Tiny)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution MooseX-Types,
version 0.51:
Organise your Moose types in libraries

%package dev
Summary: dev components for the perl-MooseX-Types package.
Group: Development
Provides: perl-MooseX-Types-devel = %{version}-%{release}
Requires: perl-MooseX-Types = %{version}-%{release}

%description dev
dev components for the perl-MooseX-Types package.


%package perl
Summary: perl components for the perl-MooseX-Types package.
Group: Default
Requires: perl-MooseX-Types = %{version}-%{release}

%description perl
perl components for the perl-MooseX-Types package.


%prep
%setup -q -n MooseX-Types-0.51
cd %{_builddir}/MooseX-Types-0.51

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/MooseX::Types.3
/usr/share/man/man3/MooseX::Types::Base.3
/usr/share/man/man3/MooseX::Types::CheckedUtilExports.3
/usr/share/man/man3/MooseX::Types::Combine.3
/usr/share/man/man3/MooseX::Types::Moose.3
/usr/share/man/man3/MooseX::Types::TypeDecorator.3
/usr/share/man/man3/MooseX::Types::UndefinedType.3
/usr/share/man/man3/MooseX::Types::Util.3
/usr/share/man/man3/MooseX::Types::Wrapper.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
